### ISSUE TITLE
Bug in parsing involving rests

### ISSUE THREAD

**Issue by mourendxu** [cutelabnyc/nested-tuplets#6]
[4 {3 1 [] 1 ['] 1 []}]

Which should be 4 beats, divided into 3, with a middle rest is parsed into 3 events. Here are the resulting onsets
0 0.333333 "1113" 0.333333 0.666667 "111" 0.666667 1 "111"

I believe this is a bug in parsing, unless I misunderstood the nestup language?

Thank you

**Comment by jinpavg** [comment]
Hi there, thank you for checking out Nestup! If I understand you
correctly, you are trying to create a container of 4 beats, divided into
3 subdivisions, with a rest on the second subdivision. If that's right,
you would need to write something like this:

[4 {3 1 [] 2 ['] 3 [] ]
In the expression you have written, `[4 {3 1 [] 1 ['] 1 []}]`, the range
start of "1" will only ever address the first subdivision in this
container. 

We could also write the expression with some shorthand:

[4 {3 1 2 ['] 3 ]
or even

[4 {3 2 ['] ]
I hope this makes sense, and thanks again,

Alex Van Gils 
he/him 

On April 18, 2021, GitHub notifications ***@***.***>
wrote:
> [4 {3 1 [] 1 ['] 1 []}]
>
> Which should be 4 beats, divided into 3, with a middle rest is parsed
> into 3 events. Here are the resulting onsets
>  0 0.333333 "1113" 0.333333 0.666667 "111" 0.666667 1 "111"
>
> I believe this is a bug in parsing, unless I misunderstood the nestup
> language?
>
> Thank you
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cutelabnyc/nested-tuplets/issues/6>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AA4R7BDDCXWIOILRAUWOQ3TTJOS4JANCNFSM43E7PXJA>.

**Comment by jinpavg** [comment]
There was a typo in the initial response, in case the edits don't come through, the correct expressions would be either of the following.

`[4 {3 1 [] 2 ['] 3 []}]`

`[4 {3 1 2 ['] 3 }]`

`[4 {3 2 ['] }]`

**Comment by mourendxu** [comment]
Ahh gotcha. So, it seems to be my misunderstanding. Thank you!
